# Generated by Django 5.2.3 on 2025-06-14 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorURL', models.URLField(unique=True)),
                ('displayName', models.CharField(max_length=150)),
                ('host', models.URLField()),
                ('github', models.URLField(blank=True, default=None)),
                ('profileImage', models.URLField(blank=True, default='https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
