# Generated by Django 5.2.3 on 2025-06-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('requester', 'requested_account', 'state')},
        ),
    ]
