# Generated by Django 5.2.3 on 2025-07-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_local',
            field=models.URLField(default=True),
        ),
    ]
