# Generated by Django 5.2.3 on 2025-06-16 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Follow', 'follow'), ('like', 'Like'), ('comment', 'Comment')], default=None, max_length=20)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='wiki.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='InboxObject',
        ),
    ]
