# Generated by Django 5.2.3 on 2025-06-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='web',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='http://"s25-project-white"/api/'),
        ),
    ]
