# Generated by Django 5.2.3 on 2025-06-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_followrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('requester', 'requested_account', 'is_deleted')},
        ),
    ]
