# Generated by Django 5.2.3 on 2025-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_author_is_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
