# Generated by Django 5.2.4 on 2025-07-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_comment_entry_url_alter_comment_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='entry_url',
        ),
    ]
