# Generated by Django 5.2.3 on 2025-06-16 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_author_is_deleted_authorfollowing_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('friended_at', models.DateTimeField(auto_now_add=True)),
                ('friended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_b', to='wiki.author')),
                ('friending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_a', to='wiki.author')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('friending', 'friended'), name='unique_friendship_pair')],
            },
        ),
    ]
