# Generated by Django 5.2.3 on 2025-06-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_followrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together={('requester', 'requested_account', 'is_deleted', 'state')},
        ),
        migrations.AddConstraint(
            model_name='followrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('requester', 'requested_account', 'state'), name='unique_active_follow_request'),
        ),
    ]
