# Generated by Django 5.2.4 on 2025-07-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_comment_entry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='remote_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wiki.entry'),
            preserve_default=False,
        ),
    ]
