# Generated by Django 5.2.4 on 2025-07-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_comment_is_local_commentlike_is_local_like_is_local'),
        ('wiki', '0003_alter_author_is_local'),
    ]

    operations = [
    ]
