# Generated by Django 5.2.4 on 2025-07-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_comment_is_local_commentlike_is_local_like_is_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
    ]
