# Generated by Django 5.2.4 on 2025-07-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_entry_origin_url'),
        ('wiki', '0004_merge_20250724_1129'),
    ]

    operations = [
    ]
