# Generated by Django 5.2.3 on 2025-06-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_followrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=set(),
        ),
    ]
