# Generated by Django 5.2.4 on 2025-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_comment_remote_url_alter_comment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, default=''),
        ),
    ]
