# Generated by Django 5.2.3 on 2025-06-18 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_entry_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wiki.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.author')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
