# Generated by Django 5.2.3 on 2025-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_entry_visibility'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authorfriend',
            name='unique_friendship_pair',
        ),
        migrations.AddConstraint(
            model_name='authorfriend',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('friending', 'friended'), name='unique_active_friendship'),
        ),
    ]
