# Generated by Django 5.2.4 on 2025-07-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_author_is_local'),
        ('wiki', '0004_remove_entry_image'),
    ]

    operations = [
    ]
