# Generated by Django 5.2.3 on 2025-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_followrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorfollowing',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='authorfollowing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('follower', 'following'), name='unique_active_following'),
        ),
    ]
