# Generated by Django 5.2.3 on 2025-06-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_followrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
    ]
