# Generated by Django 5.2.4 on 2025-07-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_merge_0002_entry_origin_url_0004_merge_20250724_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_local',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='is_local',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_local',
        ),
    ]
