# Generated by Django 5.2.3 on 2025-06-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_commentlike'),
        ('wiki', '0005_remove_authorfriend_unique_friendship_pair_and_more'),
    ]

    operations = [
    ]
