# Generated by Django 5.2.3 on 2025-06-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='web',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
