# Generated by Django 5.2.4 on 2025-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_remove_comment_is_local_remove_commentlike_is_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
