# Generated by Django 5.2.3 on 2025-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0006_merge_20250618_1642"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authorfriend",
            name="unique_active_friendship",
        ),
        migrations.AlterUniqueTogether(
            name="commentlike",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="authorfriend",
            constraint=models.UniqueConstraint(
                fields=("friending", "friended"), name="unique_active_friendship"
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"), name="unique_comment_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("entry", "user"), name="unique_active_like"
            ),
        ),
    ]
