# Generated by Django 5.2.3 on 2025-06-17 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
