# Generated by Django 5.2.3 on 2025-06-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_author_github_alter_author_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='wiki.author')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='wiki.author')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='follow')),
                ('summary', models.CharField(default='You have recieved a follow request!')),
                ('state', models.CharField(choices=[('requesting', 'Requesting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requesting', max_length=15)),
                ('requestedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followRequests', to='wiki.author')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting', to='wiki.author')),
            ],
            options={
                'unique_together': {('requester', 'requestedAccount')},
            },
        ),
    ]
