# Generated by Django 5.2.3 on 2025-06-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_remove_authorfriend_unique_active_friendship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='wiki.author'),
        ),
    ]
