# Generated by Django 5.2.4 on 2025-07-24 23:55

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_comment_is_local_commentlike_is_local_like_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, null=True, default=''),
        ),
    ]
