# Generated by Django 5.2.3 on 2025-06-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_authorfollowing_unique_together_and_more'),
        ('wiki', '0007_entry_serial'),
    ]

    operations = [
    ]
