# Generated by Django 5.2.4 on 2025-07-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_merge_20250724_1211'),
        ('wiki', '0007_comment_is_local_commentlike_is_local_like_is_local'),
    ]

    operations = [
    ]
