# Generated by Django 5.2.3 on 2025-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_comment_is_local_commentlike_is_local_like_is_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeConnectionCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
