# Generated by Django 5.2.3 on 2025-07-25 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_nodeconnectioncredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='serial',
            field=models.UUIDField(default=uuid.UUID('e293618d-f3a6-4cb9-89e8-87fd22ffc97f'), unique=True),
        ),
    ]
