# Generated by Django 5.2.3 on 2025-07-03 07:44

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_remove_authorfriend_unique_active_friendship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='created_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
    ]
