# Generated by Django 5.2.3 on 2025-07-26 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_alter_author_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='serial',
            field=models.UUIDField(default=uuid.UUID('4f06041f-366d-4f0a-a527-af712abaa2ff'), null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='serial',
            field=models.UUIDField(default=uuid.UUID('af7498d7-d1f9-4445-9943-6be323093b8e'), unique=True),
        ),
    ]
