# Generated by Django 5.2.3 on 2025-06-17 22:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
