# Generated by Django 5.2.3 on 2025-07-03 07:54

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_alter_entry_created_at_alter_inboxitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorfollowing',
            name='date_followed',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
        migrations.AlterField(
            model_name='authorfriend',
            name='friended_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='created_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='received_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
    ]
