# Generated by Django 5.2.3 on 2025-06-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_followrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorfollowing',
            name='summary',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> has followed <django.db.models.fields.related.ForeignKey>'),
        ),
    ]
