# Generated by Django 5.2.3 on 2025-07-26 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_alter_author_serial_alter_entry_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
