# Generated by Django 5.2.4 on 2025-07-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_add_description_field'),
        ('wiki', '0009_entry_description'),
        ('wiki', '0011_alter_author_serial_alter_entry_serial'),
    ]

    operations = [
    ]
