# Generated by Django 5.2.4 on 2025-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_authorfollowing_date_followed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='web',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
