# Generated by Django 5.2.4 on 2025-07-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.URLField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.URLField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
