# Generated by Django 5.2.4 on 2025-07-09 18:06

import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_alter_comment_id_alter_commentlike_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(default=wiki.models.get_mst_time),
        ),
    ]
