# Generated by Django 5.2.4 on 2025-07-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_alter_like_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='web',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
