# Generated by Django 5.2.3 on 2025-07-20 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_remotenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxItems', to='wiki.author'),
        ),
    ]
