# Generated by Django 5.2.3 on 2025-07-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_alter_inboxitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(choices=[('Follow', 'follow'), ('like', 'Like'), ('comment', 'Comment'), ('entry', 'Entry')], default=None, max_length=20),
        ),
    ]
