# Generated by Django 5.2.3 on 2025-07-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_alter_inboxitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='content',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(choices=[('Follow', 'follow'), ('like', 'Like'), ('comment', 'Comment'), ('entry', 'Entry')], max_length=20),
        ),
    ]
