# Generated by Django 5.2.3 on 2025-07-21 21:52

import django.db.models.deletion
import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_rename_content_inboxitem_body_alter_inboxitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='type',
            field=models.CharField(choices=[('Follow', 'follow'), ('like', 'Like'), ('comment', 'Comment'), ('entry', 'Entry'), ('author', 'Author')], max_length=20),
        ),
        migrations.CreateModel(
            name='RemoteFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('followerId', models.URLField()),
                ('date_followed', models.DateTimeField(default=wiki.models.get_mst_time)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remotefollowers', to='wiki.author')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('followerId', 'following'), name='unique_active_remote_following')],
            },
        ),
        migrations.CreateModel(
            name='RemoteFollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('requesterId', models.URLField()),
                ('type', models.CharField(default='follow')),
                ('summary', models.CharField(default='You have recieved a follow request!')),
                ('state', models.CharField(choices=[('requesting', 'Requesting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requesting', max_length=15)),
                ('created_at', models.DateTimeField(default=wiki.models.get_mst_time)),
                ('requested_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_follow_requests', to='wiki.author')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('requesterId', 'requested_account', 'state'), name='unique_active_remote_follow_request')],
            },
        ),
        migrations.CreateModel(
            name='RemoteFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('friendingId', models.URLField()),
                ('friended_at', models.DateTimeField(default=wiki.models.get_mst_time)),
                ('friended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_friends', to='wiki.author')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('friendingId', 'friended'), name='unique_active_remote_friendship')],
            },
        ),
    ]
