# Generated by Django 5.2.3 on 2025-07-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0024_alter_inboxitem_type_remotefollowing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotefollowrequest',
            name='requester',
            field=models.JSONField(default='Nothing'),
            preserve_default=False,
        ),
    ]
