# Generated by Django 5.2.3 on 2025-07-22 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_remotefollowrequest_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotefollowrequest',
            name='local_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_follow_requests', to='wiki.author'),
        ),
        migrations.AlterField(
            model_name='remotefollowrequest',
            name='requested_account',
            field=models.JSONField(),
        ),
    ]
