# Generated by Django 5.2.3 on 2025-07-22 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_remotefollowrequest_local_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotefollowrequest',
            name='local_profile',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, related_name='remote_follow_requests', to='wiki.author'),
            preserve_default=False,
        ),
    ]
