# Generated by Django 5.2.4 on 2025-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0028_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
