# Generated by Django 5.2.4 on 2025-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0030_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
