# Generated by Django 5.2.3 on 2025-07-23 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0031_alter_author_profileimage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='remotefollowing',
            name='unique_active_remote_following',
        ),
        migrations.AddField(
            model_name='remotefollowing',
            name='follower',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotefollowing',
            name='local_profile',
            field=models.ForeignKey(default='http://127.0.0.1:8000/s25-project-white/api/authors/f61d4bea-7b69-4df0-a204-10b37714081d', on_delete=django.db.models.deletion.CASCADE, related_name='remotefollowers', to='wiki.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remotefollowing',
            name='following',
            field=models.JSONField(),
        ),
        migrations.AddConstraint(
            model_name='remotefollowing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('follower', 'following'), name='unique_active_remote_following'),
        ),
    ]
